export const AUTHENTICATION_COMPLETED = 'AUTHENTICATION_COMPLETED';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
export const AUTHENTICATION_STARTED = 'AUTHENTICATION_STARTED';

export const FIND_ORDER_COMPLETED = 'FIND_ORDER_COMPLETED';
export const FIND_ORDER_FAILED = 'FIND_ORDER_FAILED';
export const FIND_ORDER_STARTED = 'FIND_ORDER_STARTED';

export const GET_ORDER_COMPLETED = 'GET_ORDER_COMPLETED';
export const GET_ORDER_FAILED = 'GET_ORDER_FAILED';
export const GET_ORDER_STARTED = 'GET_ORDER_STARTED';

export const LOAD_CONFIG_COMPLETED = 'LOAD_CONFIG_COMPLETED';
export const LOAD_CONFIG_FAILED = 'LOAD_CONFIG_FAILED';
export const LOAD_CONFIG_STARTED = 'LOAD_CONFIG_STARTED';

export const ORDER_SEARCH_COMPLETED = 'ORDER_SEARCH_COMPLETED';
export const ORDER_SEARCH_FAILED = 'ORDER_SEARCH_FAILED';
export const ORDER_SEARCH_STARTED = 'ORDER_SEARCH_STARTED';

export const RESET_TRACKER_STATE = 'RESET_TRACKER_STATE';

export const SEND_PAGE_VIEW_COMPLETED = 'SEND_PAGE_VIEW_COMPLETED';
export const SEND_PAGE_VIEW_FAILED = 'SEND_PAGE_VIEW_FAILED';
export const SEND_PAGE_VIEW_STARTED = 'SEND_PAGE_VIEW_STARTED';

export const STARTUP_COMPLETED = 'STARTUP_COMPLETED';
export const STARTUP_FAILED = 'STARTUP_FAILED';
export const STARTUP_STARTED = 'STARTUP_STARTED';
